### ISSUE TITLE
DOGE transaction format not recognized

### ISSUE THREAD

**Issue by CodaSiren** [hybrix-io/hybrixd-node#8]
The following DOGE transaction cannot be found using the Explorer:
`e1d38a5e3bc0c04eca07582258368d3037d8ffc19a523b1551c6f3a22d991da7`
[Link to explorer](https://explorer.hybrix.io/?&transactionId=e1d38a5e3bc0c04eca07582258368d3037d8ffc19a523b1551c6f3a22d991da7&symbol=doge&currency=USD)

The transaction is valid, as seen [here on dogechain.info](https://dogechain.info/tx/e1d38a5e3bc0c04eca07582258368d3037d8ffc19a523b1551c6f3a22d991da7)

**Comment by agent725** [comment]
Took some bughunting, but we found the problem in the way JSON objects were read in the TCP library. We've patched the library.
